### ISSUE TITLE
Update message?

### ISSUE THREAD

**Issue by gurpal2000** [ironiemix/dokuwiki-plugin-menu#2]
I have the latest plugin installed yet DokuWiki says
"Update: New version 2017-03-12 is available."

When the update button button is pressed, nothing happens.

Is the message/metadata stale?

thanks

**Comment by zioth** [comment]
This can be fixed by adding plugin.info.text. Here's an example from the data plugin:

```
base    data
author  Andreas Gohr
email   andi@splitbrain.org
date    2017-02-08
name    Structured Data Plugin
desc    Add and query structured data in your wiki
url     https://www.dokuwiki.org/plugin:data
```

**Comment by ironiemix** [comment]
In the menu plugin this is directly in the code:

```
function getInfo(){
        return array(
            'author' => 'Matthias Grimm',
            'email'  => 'matthiasgrimm@users.sourceforge.net',
            'date'   => '2009-07-25',
            'name'   => 'Menu Plugin',
            'desc'   => 'Shows a list of links as a nice menu card',
            'url'    => 'http://www.dokuwiki.org/wiki:plugins',
        );
    }

```
Needs an update there. Beforhand, we schould check, if the original authors plugin is dead indeed, as this is an fork of an old  plugin not maintained on github.

**Comment by zioth** [comment]
Fix: https://github.com/ironiemix/dokuwiki-plugin-menu/pull/8
