### ISSUE TITLE
Horizontal menu does not wrap

### ISSUE THREAD

**Issue by ironiemix** [ironiemix/dokuwiki-plugin-menu#6]
I am using 

`<menu col=1,align=left,caption="",type="menubar">`

for a top menu, the menu does not wrap in morde than on line when the browser window is narrowed.

![nowrap](https://user-images.githubusercontent.com/516311/49073089-eb4fe080-f231-11e8-8aaf-911aab61a89c.png)

**Comment by zioth** [comment]
Easy to fix

**Comment by zioth** [comment]
Fixed: https://github.com/ironiemix/dokuwiki-plugin-menu/pull/8

**Comment by zioth** [comment]
Any chance you could add me as a contributor, so I don't have to fork? (but I'll still keep out of the master branch).

**Comment by ironiemix** [comment]
Yep. Done, you should have an invite.
